feat: add test runners to docker-compose
wmde/wikibase-metadata pull request #38
Opened 2024-10-29 13:54 UTC by rti

2024-10-29 14:19 UTC, RickiJay-WMDE requested changes

2024-10-29 14:19 UTC, RickiJay-WMDE commented on docker-compose.yml
> +      - --order-dependencies
The data tests are order-independent and don't have coverage - these should be removed

2025-01-14 11:40 UTC, RickiJay-WMDE commented on docker-compose.yml
> +      - html:cov_html
This generates a coverage report in the `cov_html` directory - would you need to use a volume so that those were legible outside of the Docker container, and is that a desirable outcome?

2025-01-20 13:00 UTC, rti commented on docker-compose.yml
> +      - html:cov_html
```yml
  test-not-data:
    volumes:
      - type: bind
        source: .
        target: /workspace
```

`.` is mounted anyway. So it will end up in the working dir already.

2025-01-22 12:32 UTC, RickiJay-WMDE approved these changes

2025-01-23 08:17 UTC, merged